# coding=utf-8
"""
Django settings for stgospel project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import re
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


ugettext = lambda s: s

#EMAIL_USE_TLS = True
EMAIL_HOST = 'localhost'
SERVER_EMAIL = 'noreply@st-gospel.ru'
DEFAULT_FROM_EMAIL = ugettext('Чтение священного писания <noreply@st-gospel.ru>')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'st.gospel.ru@gmail.com'
EMAIL_PORT = 587

EMAIL_BLACKLIST_FILE = os.path.join(BASE_DIR, "email_blacklist.txt")
USER_BLACKLIST_FILE = os.path.join(BASE_DIR, "user_blacklist.txt")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bme9jwupip@q)(lj%@*m!(esc8n!3cam)s$t!1@_rbj8o+t+9f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "www.st-gospel.ru",
    "st-gospel.ru",
]


ADMINS = (
)


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': None,
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

SESSION_COOKIE_AGE = 31449600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authuser.apps.AuthuserConfig',
    'bible.apps.BibleConfig',
    'search.apps.SearchConfig',
    'gospel.apps.GospelConfig',
    'epub.apps.EpubConfig',
    'forum.apps.ForumConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'stgospel.middleware.PageCounterMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'stgospel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': False,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bible.context_processors.volumes',
                'gospel.context_processors.groups',
                'gospel.context_processors.counter',
                'gospel.context_processors.user_today_date',
            ],
        },
    },
]

WSGI_APPLICATION = 'stgospel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'stgospel',
        'USER': 'gospel',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'CONN_MAX_AGE': 25200,
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


MONGODB = {
    "host": "localhost",
    "port": 27017
}


AUTH_USER_MODEL = 'authuser.User'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_NEXT = '/'
LOGIN_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_ROOT = '/home/www/static/st-gospel/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/www/media/st-gospel/media/'
EPUB_ROOT = "/home/www/media/st-gospel/epub/"
EPUB_SRC = os.path.join(BASE_DIR, "epub", "book")

ADMIN_MEDIA_ROOT = '/home/www/opt/python/lib/python3.6/site-packages/django/contrib/admin/static/admin'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "formatters": {
        "message": {
            "format": "%(asctime)s [%(levelname)s] %(pathname)s:%(lineno)s %(message)s"
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/home/www/logs/st-gospel/django.log',
            "formatter": "message"
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True
        },
    },
    'loggers': {
        'stgospel': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'bible': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'gospel': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "propagate": True
        },
        "django.db.backends": {
            "handlers": ["file"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}


FORUM_LANGS = (
    ('en', "English"),
    ('ru', "Русский"),
)
FORUM_LANGS_CODES = [lg[0] for lg in FORUM_LANGS]
FORUM_UPLOAD_PATH = "images/forum/upload"


IMAGES_URL = STATIC_URL + 'images/'
DEFAULT_128 = IMAGES_URL + 'default_128.png'
DEFAULT_32 = IMAGES_URL + 'default_32.png'
IMAGE_EXT = ("jpg", "jpeg", "png", "gif")
IMAGE_SIZE = 1024 * 1024


RE_TRAPEZA = re.compile(r'print_trapeza\(\)[^"]+"(.*)"\);')
RE_FEOFAN = re.compile(r'print_feofan\(\)[^"]+"(.*)"\);')

CALENDAR_URL = "http://calendar.rop.ru/"
CALENDAR_PARAM = "idd"
CALENDAR_PARAM_FROM = 1
CALENDAR_PARAM_TO = 378
CALENDAR_YEAR = 2025
CALENDAR_PARSE_FINISHED_DATE = datetime.date(2026, 1, 14)

CALENDAR_DIR = os.path.join(BASE_DIR, "gospel", "calendar", str(CALENDAR_YEAR))
CALENDAR_SCRIPT = os.path.join(CALENDAR_DIR, "script")
CALENDAR_SRC = os.path.join(CALENDAR_DIR, "src")
CALENDAR_YEAR_DIR = os.path.join(CALENDAR_DIR, "json")

TROPARION_PATH = os.path.join(BASE_DIR, 'prayer', 'troparion')
HOLYDAY_DATA = os.path.join(TROPARION_PATH, 'holyday.json')
PRAYER_GENERIC_DATA = os.path.join(TROPARION_PATH, 'generic.json')

CITIES_SRC_FILE = os.path.join(BASE_DIR, "authuser", "cities.csv")
CITIES_FILE = os.path.join(BASE_DIR, "authuser", "cities.json")
CITIES_FILTER_FILE = os.path.join(BASE_DIR, "authuser", "cities_filter.json")

