# Generated by Django 4.0.5 on 2023-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
