# Generated by Django 2.0.4 on 2018-05-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('link', models.CharField(max_length=8, unique=True, verbose_name='Внешняя ссылка')),
                ('public', models.BooleanField(default=False)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Администратор'), ('U', 'Участник')], default='U', max_length=1, verbose_name='Роль')),
                ('joined', models.DateField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('deleted', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.AgreementGroup')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('new_member', 'новый пользователь добавился в группу'), ('title', 'изменено названия группы'), ('startidx', 'изменена начальная глава чтения'), ('chpd', 'изменено количество глав чтения в день'), ('namescnt', 'изменено максимальное количество имен в списке'), ('date', 'изменена дата начала (или окончания) чтения'), ('rem_pray', 'удалена молитва из группы'), ('add_start_pray', 'добавлена молитва в начало'), ('add_end_pray', 'добавлена молитва в конец'), ('add_div', 'добавлен новый список с именами'), ('del_div', 'удален список с именами'), ('div_name', 'изменено имя списка с именами'), ('prayfor_name', 'изменено имя в списке'), ('prayfor_till', 'изменена дата окончания для имени в списке'), ('add_prayfor', 'добавлено имя в список'), ('rem_prayfor', 'удалено имя из списка')], max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.AgreementGroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя нуждающегося')),
                ('rip', models.BooleanField(default=False, verbose_name='О упокоении')),
                ('till', models.DateField(blank=True, null=True, verbose_name='Поминать до')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrayForDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя молящегося')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.AgreementGroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False, verbose_name='В начале')),
                ('end', models.BooleanField(default=False, verbose_name='В конце')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.AgreementGroup')),
                ('pray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Pray')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_idx', models.PositiveSmallIntegerField(default=1, verbose_name='Начальный индекс последовательности')),
                ('chpd', models.PositiveSmallIntegerField(default=1, verbose_name='Количество глав в день')),
                ('names_cnt', models.PositiveSmallIntegerField(default=0, verbose_name='Количество имен в списке')),
                ('start', models.DateField(verbose_name='Дата начала чтения')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата завершения перерыва')),
            ],
        ),
        migrations.AddField(
            model_name='prayfor',
            name='div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.PrayForDiv'),
        ),
        migrations.AddField(
            model_name='agreementgroupuser',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gospel.Settings'),
        ),
        migrations.AddField(
            model_name='agreementgroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementgroup',
            name='prays',
            field=models.ManyToManyField(through='gospel.PrayGroup', to='bible.Pray'),
        ),
        migrations.AddField(
            model_name='agreementgroup',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel.Settings'),
        ),
        migrations.AddField(
            model_name='agreementgroup',
            name='users',
            field=models.ManyToManyField(through='gospel.AgreementGroupUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementgroup',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Volume'),
        ),
        migrations.AlterUniqueTogether(
            name='praygroup',
            unique_together={('pray', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='agreementgroupuser',
            unique_together={('group', 'user')},
        ),
    ]
