# Generated by Django 2.0.4 on 2018-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayfor',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('new_member', 'новый пользователь добавился в группу'), ('title', 'изменено названия группы'), ('startidx', 'изменена начальная глава чтения'), ('chpd', 'изменено количество глав чтения в день'), ('namescnt', 'изменено максимальное количество имен в списке'), ('date', 'изменена дата начала (или окончания) чтения'), ('rem_pray', 'удалена молитва из группы'), ('add_start_pray', 'добавлена молитва в начало'), ('add_end_pray', 'добавлена молитва в конец'), ('sort_start_pray', 'изменен порядок молитв в начале'), ('sort_end_pray', 'изменен порядок молитв в конце'), ('add_div', 'добавлен новый список с именами'), ('del_div', 'удален список с именами'), ('div_name', 'изменено имя списка с именами'), ('prayfor_name', 'изменено имя в списке'), ('prayfor_till', 'изменена дата окончания для имени в списке'), ('add_prayfor', 'добавлено имя в список'), ('rem_prayfor', 'удалено имя из списка')], max_length=30),
        ),
    ]
