# Generated by Django 2.1 on 2019-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0003_auto_20180608_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='listorder',
            field=models.CharField(choices=[('A', 'после всех глав'), ('B', 'между главами')], default='B', max_length=1),
        ),
    ]
