# Generated by Django 2.2.5 on 2020-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0004_settings_listorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayfor',
            name='list_type',
            field=models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих')], default='H', max_length=1, verbose_name='Тип списка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreementgroupuser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('E', 'Редактор'), ('U', 'Участник')], default='U', max_length=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('new_member', 'новый пользователь добавился в группу'), ('rem_member', 'пользователь покинул группу'), ('title', 'изменено названия группы'), ('startidx', 'изменена начальная глава чтения'), ('chpd', 'изменено количество глав чтения в день'), ('namescnt', 'изменено максимальное количество имен в списке'), ('date', 'изменена дата чтения'), ('rem_pray', 'удалена молитва из группы'), ('add_start_pray', 'добавлена молитва в начало'), ('add_end_pray', 'добавлена молитва в конец'), ('sort_start_pray', 'изменен порядок молитв в начале'), ('sort_end_pray', 'изменен порядок молитв в конце'), ('add_div', 'добавлен новый список с именами'), ('del_div', 'удален список с именами'), ('sort_div', 'изменен порядок в списке с именами'), ('div_name', 'изменено имя списка с именами'), ('prayfor_name', 'изменено имя в списке'), ('prayfor_till', 'изменена дата окончания для имени в списке'), ('add_prayfor', 'добавлено имя в список'), ('rem_prayfor', 'удалено имя из списка'), ('listorder', 'изменен порядок следования списков поминовения при чтении')], max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возобновления чтения'),
        ),
    ]
