# Generated by Django 2.2.5 on 2020-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0005_auto_20200325_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayfordiv',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
