# Generated by Django 2.2.5 on 2020-03-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0006_prayfordiv_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayfor',
            name='rip',
        ),
    ]
