# Generated by Django 3.1.2 on 2021-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0007_remove_prayfor_rip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='agreementgroup',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='agreementgroup',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='prayfor',
            name='list_type',
            field=models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих'), ('W', 'О враждующих')], max_length=1, verbose_name='Тип списка'),
        ),
    ]
