# Generated by Django 3.1.7 on 2021-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0007_remove_prayfor_rip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='agreementgroup',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='agreementgroup',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('new_member', 'новый пользователь добавился в группу'), ('rem_member', 'пользователь покинул группу'), ('title', 'изменено названия группы'), ('startidx', 'изменена начальная глава чтения'), ('chpd', 'изменено количество глав чтения в день'), ('namescnt', 'изменено максимальное количество имен в списке'), ('date', 'изменена дата чтения'), ('rem_pray', 'удалена молитва из группы'), ('add_start_pray', 'добавлена молитва в начало'), ('add_end_pray', 'добавлена молитва в конец'), ('sort_start_pray', 'изменен порядок молитв в начале'), ('sort_end_pray', 'изменен порядок молитв в конце'), ('add_div', 'добавлен новый список с именами'), ('del_div', 'удален список с именами'), ('sort_div', 'изменен порядок в списке с именами'), ('div_name', 'изменено имя списка с именами'), ('prayfor_name', 'изменено имя в списке'), ('prayfor_till', 'изменена дата окончания для имени в списке'), ('add_prayfor', 'добавлено имя в список'), ('rem_prayfor', 'удалено имя из списка'), ('change_role', 'изменена роль участника'), ('listorder', 'изменен порядок следования списков поминовения при чтении')], max_length=30),
        ),
        migrations.AlterField(
            model_name='prayfor',
            name='list_type',
            field=models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих'), ('W', 'О враждующих')], max_length=1, verbose_name='Тип списка'),
        ),
    ]
