# Generated by Django 4.0 on 2022-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0008_auto_20210213_1204'),
        ('gospel', '0008_auto_20210402_2025'),
    ]

    operations = [
    ]
