# Generated by Django 4.0 on 2022-04-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0009_merge_0008_auto_20210213_1204_0008_auto_20210402_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementgroup',
            options={'verbose_name': 'Чтение', 'verbose_name_plural': 'Чтения'},
        ),
        migrations.AlterField(
            model_name='agreementgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название чтения (группы)'),
        ),
    ]
