# Generated by Django 4.0.5 on 2022-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gospel', '0010_alter_agreementgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='prayfor',
            name='list_type',
            field=models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих'), ('W', 'О враждующих'), ('A', 'О воинах')], max_length=1, verbose_name='Тип списка'),
        ),
    ]
