# Generated by Django 2.1 on 2018-11-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20181122_1527'),
        ('authuser', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('pray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Pray')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
