# Generated by Django 3.1.7 on 2021-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_auto_20181122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
