# Generated by Django 3.1.2 on 2021-02-13 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_auto_20181122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Synodik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя нуждающегося')),
                ('list_type', models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих'), ('W', 'О враждующих')], max_length=1, verbose_name='Тип списка')),
                ('till', models.DateField(blank=True, null=True, verbose_name='Поминать до')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
