# Generated by Django 4.0 on 2022-04-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_merge_0004_auto_20210213_1204_0004_auto_20210402_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz_city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город из часового пояса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='Europe/Moscow', max_length=100, verbose_name='Часовой пояс'),
        ),
    ]
