# Generated by Django 4.0.5 on 2022-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_user_tz_city_alter_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synodik',
            name='list_type',
            field=models.CharField(choices=[('H', 'О здравии'), ('R', 'О упокоении'), ('S', 'О болящих'), ('W', 'О враждующих'), ('A', 'О воинах')], max_length=1, verbose_name='Тип списка'),
        ),
    ]
