# Generated by Django 4.0.5 on 2023-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_alter_synodik_list_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
