# Generated by Django 2.0.4 on 2018-05-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('chapters', models.PositiveSmallIntegerField(default=0)),
                ('has_foreword', models.BooleanField(default=False)),
                ('has_notes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('lines', models.PositiveSmallIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=4000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Pray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название молитвы')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('text', models.TextField()),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Молитва',
                'verbose_name_plural': 'Молитвы',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название цикла чтения')),
                ('public', models.BooleanField(default=False)),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Volume')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VolumeChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название собрания глав')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VolumeItemChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Chapter')),
                ('volumechapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.VolumeChapters')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeItemLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Line')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название собрания стихов')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lines', models.ManyToManyField(through='bible.VolumeItemLine', to='bible.Line')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Volume')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VolumePray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Pray')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Volume')),
            ],
        ),
        migrations.AddField(
            model_name='volumeitemline',
            name='volumelines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.VolumeLines'),
        ),
        migrations.AddField(
            model_name='volumechapters',
            name='chapters',
            field=models.ManyToManyField(through='bible.VolumeItemChapter', to='bible.Chapter'),
        ),
        migrations.AddField(
            model_name='volumechapters',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Volume'),
        ),
        migrations.AlterUniqueTogether(
            name='volumepray',
            unique_together={('volume', 'pray')},
        ),
        migrations.AlterUniqueTogether(
            name='volumeitemline',
            unique_together={('volumelines', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='volumeitemchapter',
            unique_together={('volumechapters', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='volumebook',
            unique_together={('volume', 'book')},
        ),
    ]
