# Generated by Django 2.1 on 2019-03-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20181122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
