# Generated by Django 2.1 on 2019-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_book_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
