# Generated by Django 3.1.7 on 2021-04-02 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_volume_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
