# Generated by Django 4.0 on 2022-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0005_auto_20210402_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Сборник', 'verbose_name_plural': 'Сборники'},
        ),
    ]
