# Generated by Django 4.0.5 on 2023-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0006_alter_volume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumelines',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название собрания стихов'),
        ),
    ]
