# Generated by Django 4.0.5 on 2023-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0007_alter_volumelines_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumelines',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название собрания стихов'),
        ),
    ]
