# Generated by Django 4.0.10 on 2024-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0008_alter_volumelines_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumelines',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='volumelines',
            name='volume',
        ),
        migrations.AddField(
            model_name='volumeitemchapter',
            name='lines',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.DeleteModel(
            name='VolumeItemLine',
        ),
        migrations.DeleteModel(
            name='VolumeLines',
        ),
    ]
